Fix doc dependencies (#355)
* Fixed minimum required setuptools version

Build error on RTD:
Processing dependencies for glotaran==0.0.16
error: setuptools 41.0.1 is installed but setuptools>=41.2 is required by {'xarray'}

* Pinned version of setuptools in requirements_dev.txt

Since the minversion it is a requirement of setup.py, this version should be fixed, so dependabot PR's inform us when there is a problem again. This is for manually updating only, and the dependabot PR's should be deactivated for setuptools

---
Thanks @s-weigand