🧰 Use ruff as linter (#1379)
Adds ruff config and adapt to new rules.

* 🧰 Add minimal ruff config
🧹🩹 Fix issues detected by ruff
* 🧰👌 Add T20 ruff rule
* 🧰👌 Add YTT and PGH ruff rules
* 🧰👌 Add ISC ruff rule
* 🧰👌 Add C4, T10 and FA ruff rules
* 🧰👌 Add PIE ruff rule
* 🧰👌 Add NPY ruff rule
* 🧰👌 Add RSE ruff rule
* 🧰👌 Add PD ruff rule
* 🧰👌 Add RET ruff rule
* 🧰👌 Add SIM ruff rule
* 🧰👌 Add INP ruff rule
* 🧰👌 Add TCH ruff rule

Note that we need to ignore this rule for types that are used to define pydantic acctributes or the pydantic models will ony get partially defined.
Errors caused by this look as follows:
pydantic.errors.PydanticUserError: `<pydantic-class>` is not fully defined; you should define `<type-of-attribute>`, then call `<pydantic-class>.model_rebuild()`.

* 🧰👌 Add PTH ruff rule
* 🧰👌 Add BLE ruff rule

* 🩹 Fix glotaran.builtin.items being an implicit name namespace package
* 🤖  Refactored by Sourcery

---------

Co-authored-by: Sourcery AI <>