🧪 Add tests for add_svd_to_dataset
The test `test_add_svd_to_dataset_works_with_transposed_data`reproduces a crash when the order of lsv_dim and rsv_dim is different than in the onderlaying numpy array.
Causing:
xarray.structure.alignment.AlignmentError: cannot reindex or align along dimension 'time' because of conflicting dimension sizes: {2, 3} (note: an index is found along that dimension with size=3)