🩹 Fix OSError in load_scheme on linux due to too long Path
Path.is_file uses the stat descriptor which causes:

OSError: [Errno 36] File name too long

for a yml_str scheme