🩹 Fix missing installation of clp-guide megacomplex as plugin
This bug wasn't cough by the test since the tests import `glotaran.builtin.megacomplexes.clp_guide` which is equivalent to installing the plugin.

When normally using it the error was:
ValueError: Unknown megacomplex type 'clp-guide'. Known megacomplex types are: ['baseline', 'coherent-artifact', 'damped-oscillation', 'decay', 'decay-parallel', 'decay-sequential', 'glotaran.builtin.megacomplexes.baseline.baseline_megacomplex.BaselineMegacomplex', 'glotaran.builtin.megacomplexes.coherent_artifact.coherent_artifact_megacomplex.CoherentArtifactMegacomplex', 'glotaran.builtin.megacomplexes.damped_oscillation.damped_oscillation_megacomplex.DampedOscillationMegacomplex', 'glotaran.builtin.megacomplexes.decay.decay_megacomplex.DecayMegacomplex', 'glotaran.builtin.megacomplexes.decay.decay_parallel_megacomplex.DecayParallelMegacomplex', 'glotaran.builtin.megacomplexes.decay.decay_sequential_megacomplex.DecaySequentialMegacomplex', 'glotaran.builtin.megacomplexes.spectral.spectral_megacomplex.SpectralMegacomplex', 'spectral']