⬆️ Bump numpy from 1.26.4 to 2.0.1 (#1523)
* Bump numpy from 1.26.4 to 2.1.0

Bumps [numpy](https://github.com/numpy/numpy) from 1.26.4 to 2.1.0.
- [Release notes](https://github.com/numpy/numpy/releases)
- [Changelog](https://github.com/numpy/numpy/blob/main/doc/RELEASE_WALKTHROUGH.rst)
- [Commits](https://github.com/numpy/numpy/compare/v1.26.4...v2.1.0)

---
updated-dependencies:
- dependency-name: numpy
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* 🩹 Fix repr issue with numpy>2 str values

This caused the following test error:
```py
FAILED glotaran/utils/test/test_io.py::test_create_clp_guide_dataset_errors - assert "Unknown clp_...'species_3')]" == "Unknown clp_... 'species_3']"

  Skipping 49 identical leading characters in diff, use -v to show
    ls are:
  -  ['species_1', 'species_2', 'species_3']
  +  [np.str_('species_1'), np.str_('species_2'), np.str_('species_3')]
```

* ⬆️ Correct minor version of numpy

numpy 2.1 is not yet supported be e.g. numba

* Use .to_numpy instead of .values

* 🩹 Use add_svd_to_dataset instead of duplication with error

This way we can reuse code and fixes and don't have the extra duplication and maintenance burden

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: s-weigand <s.weigand.phy@gmail.com>
Co-authored-by: Joris Snellenburg <jsnel@users.noreply.github.com>