Added target model to tests/python/fit_data_in_vivo_cyano_data.py -> new issue
The issue's error log is:

WinPython\virtenv\virtenv361\Scripts\python.exe glotaran/tests/python/fit_data_in_vivo_cyano_data.py
Traceback (most recent call last):
  File "glotaran/tests/python/fit_data_in_vivo_cyano_data.py", line 362, in <module>
    target_analysis_result = specfit_model_target.fit()
  File "glotaran\glotaran\model\model.py", line 45, in fit
    return self.fit_model().fit(nnls, *args, **kwargs)
  File "glotaran\glotaran\fitmodel\fitmodel.py", line 22, in fit
    result = self.result(nnls, *args, **kwargs)
  File "glotaran\glotaran\fitmodel\fitmodel.py", line 29, in result
    self._model.
  File "glotaran\glotaran\fitmodel\matrix_group_generator.py", line 16, in for_model
    gen._init_groups_for_model(model, xtol)
  File "glotaran\glotaran\fitmodel\matrix_group_generator.py", line 28, in _init_groups_for_model
    self._add_dataset_to_group(model, dataset, xtol)
  File "glotaran\glotaran\fitmodel\matrix_group_generator.py", line 34, in _add_dataset_to_group
    in grouping_axis]:
  File "glotaran\glotaran\fitmodel\matrix_group_generator.py", line 33, in <listcomp>
    for matrix in [self._matrix(x, dataset, model) for x
  File "glotaran\glotaran\models\spectral_temporal\kinetic_c_matrix.py", line 22, in __init__
    self._collect_k_matrices(model)
  File "glotaran\glotaran\models\spectral_temporal\kinetic_c_matrix.py", line 56, in _collect_k_matrices
    model_k_matrix = model_k_matrix.combine(m)
  File "glotaran\glotaran\models\spectral_temporal\k_matrix.py", line 73, in combine
    combined_matrix)
TypeError: __init__() missing 1 required positional argument: 'compartments'