Fixed minimum required setuptools version
Build error on RTD:
Processing dependencies for glotaran==0.0.16
error: setuptools 41.0.1 is installed but setuptools>=41.2 is required by {'xarray'}