Removed redundant definition of fit_model_class
glotaran\models\spectral_temporal\model_kinetic.py:94:5: F811 redefinition of unused 'fit_model_class' from line 50