🧹🚇 Remove asv benchmarks and binder integration (#1511)
* 🧹 Remove ASV benchmarks
Since the 0.8 rewrite will drop ASV benchmarks there is no point in sticking to them and maintaining them on `main`.
* 🧹 Remove binder integration
Binder has not been functional for quite some time (startup timeout), so there is no point in keeping it.
* 🚧📚 Added change to changelog
* 🩹 Fix mypy pre-commit env setup issue
All versions of the package `types-pkg-resources` (dependency of `types-all`) were yanked causing the following error when `pre-commit` tries to create the `mypy` venv.

```py
stderr:
    ERROR: Ignored the following yanked versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3
    ERROR: Could not find a version that satisfies the requirement types-pkg-resources (from types-all) (from versions: none)
    ERROR: No matching distribution found for types-pkg-resources
```
* 🧹 Fix unused type ignore that mypy found after removing types-all